version: "3.7"

services:
  app:
    image: edgarolivar16/app_vuelos:v2
    container_name: app_vuelos
    env_file: .env
    ports:
      - 80:3000
    restart: always
    networks:
      - ms_nestjs

  flight-ms:
    image: edgarolivar16/flight-ms:v2
    container_name: flight-ms
    env_file: .env
    restart: always
    networks:
      - ms_nestjs

  passenger-ms:
    image: edgarolivar16/passenger-ms:v2
    container_name: passenger-ms
    env_file: .env
    restart: always
    networks:
      - ms_nestjs

  user-ms:
    image: edgarolivar16/user-ms:v2
    container_name: user-ms
    env_file: .env
    restart: always
    networks:
      - ms_nestjs

networks:
  ms_nestjs:
